### ISSUE TITLE
Make a hiring page

### ISSUE THREAD

**Issue by harsh-not-haarsh** [harsh-not-haarsh/arEd#3]
- [ ] form to accept people's name, email and Linkedin profile
- [ ] make it beautiful (we need to attract top talent)

**Comment by Shreya-IITJ** [comment]
I am interested in taking up this issue. Please assign it to me.

**Comment by shivalee12** [comment]
I am interested in taking up this issue
can you pls assign it to me

**Comment by harsh-not-haarsh** [comment]
done.
